version: '3' #docker version
services:
  db:
    # image: mysql:latest
    container_name: db
    build: 
      context: ./db
      dockerfile: Dockerfile
    environment:
      - MYSQL_DATABASE=EMSDB
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password # this should live in a env var
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 # equivalent to True
    ports:
      - 9999:3306
    volumes:
      - "../db:/docker-entrypoint-initdb.d" #sync persistent sql files with continer
    # command: bash -c chmod -R 777 /docker-entrypoint-initdb.d/
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
